/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_behavior_free: (a: number, b: number) => void;
export const __wbg_event_free: (a: number, b: number) => void;
export const __wbg_subscription_free: (a: number, b: number) => void;
export const behavior: (a: any) => number;
export const behavior_combine: (a: number, b: number, c: any) => [number, number, number];
export const behavior_map: (a: number, b: any) => [number, number, number];
export const behavior_new: (a: any) => number;
export const behavior_sample: (a: number) => any;
export const behavior_set: (a: number, b: any) => void;
export const behavior_subscribe: (a: number, b: any) => number;
export const behavior_update: (a: number, b: any) => [number, number];
export const combine: (a: number, b: number, c: any) => [number, number, number];
export const constant: (a: any) => number;
export const event: () => number;
export const event_emit: (a: number, b: any) => void;
export const event_filter: (a: number, b: any) => number;
export const event_fold: (a: number, b: any, c: any) => [number, number, number];
export const event_map: (a: number, b: any) => number;
export const event_merge: (a: number, b: number) => number;
export const event_new: () => number;
export const event_subscribe: (a: number, b: any) => number;
export const ifElse: (a: number, b: any, c: any) => [number, number, number];
export const init: () => void;
export const subscription_unsubscribe: (a: number) => void;
export const version: () => [number, number];
export const when: (a: number, b: any) => [number, number, number];
export const wasm_bindgen__convert__closures_____invoke__h616a2fe72366c77a: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h0e74ad10628768ff: (a: number, b: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
