/**
 * Type declarations for the WASM module.
 *
 * These types are used for TypeScript compilation when the WASM
 * package hasn't been built yet (e.g., in CI type checking).
 *
 * The actual implementation is generated by wasm-pack in ../pkg/
 */

declare module '../pkg/cliffy_wasm.js' {
  /** Initialize the WASM module */
  export default function init(): Promise<void>;

  /** Get the version string */
  export const version: string;

  /** WASM Behavior class */
  export class Behavior {
    constructor(initial: unknown);
    sample(): unknown;
    set(value: unknown): void;
    update(f: (value: unknown) => unknown): void;
    subscribe(callback: (value: unknown) => void): Subscription;
    map(f: (value: unknown) => unknown): Behavior;
    combine(other: Behavior, f: (a: unknown, b: unknown) => unknown): Behavior;
  }

  /** WASM Event class */
  export class Event {
    constructor();
    emit(value: unknown): void;
    subscribe(callback: (value: unknown) => void): Subscription;
    map(f: (value: unknown) => unknown): Event;
    filter(predicate: (value: unknown) => boolean): Event;
    merge(other: Event): Event;
    fold(initial: unknown, f: (acc: unknown, value: unknown) => unknown): Behavior;
  }

  /** WASM Subscription class */
  export class Subscription {
    unsubscribe(): void;
  }

  /** Create a behavior with an initial value */
  export function behavior(initial: unknown): Behavior;

  /** Create an event stream */
  export function event(): Event;

  /** Conditional combinator */
  export function when(condition: Behavior, thenValue: () => unknown): Behavior;

  /** If-else combinator */
  export function ifElse(
    condition: Behavior,
    thenValue: () => unknown,
    elseValue: () => unknown
  ): Behavior;

  /** Combine two behaviors */
  export function combine(
    a: Behavior,
    b: Behavior,
    f: (a: unknown, b: unknown) => unknown
  ): Behavior;

  /** Create a constant behavior */
  export function constant(value: unknown): Behavior;
}
